####################################################################################################
# server
####################################################################################################
server:
  error: 
    include-exception: true
    include-stacktrace: always
  use-forward-headers: true

####################################################################################################
# spring
####################################################################################################
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
  profiles:
    active: debug
  thymeleaf:
    mode: HTML
#  output:
#    ansi:
#      enabled: ALWAYS
  security.oauth2.client.registration:
    google:
      client-id: xxxxx
      client-secret: xxxxx
  jmx:
    enable: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    hibernate:
      ddl-auto: validate

####################################################################################################
# management
####################################################################################################
management.endpoints:
    jmx.exposure:
        include: '*'
        exclude: shutdown
    web.exposure:
        include: '*'
        exclude: shutdown
